### ISSUE TITLE
disturb_numb

### ISSUE THREAD

**Issue by gplminhduc147** [JiatongBao/DRLSorting#1]
Hello. When I run the trainning code. I've got this error:

**Traceback (most recent call last):
  File "main.py", line 769, in <module>
    main(args)
  File "main.py", line 31, in main
    disturb_num = args.disturb_num
AttributeError: 'Namespace' object has no attribute 'disturb_num'**

What should I do to fix this error? Thank you so much

**Comment by JiatongBao** [comment]
Please set: disturb_num = 0. This parameter was not used in simulation.

**Comment by gplminhduc147** [comment]
Thank you for your help. I set disturb_num = 0 and the simulation worked well.
