### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by DucNguyenAIML** [JiatongBao/DRLSorting#2]
I run the trainning code and get the error: CUDA out of memory
I've already check the **Issues** discussion in VPG by AndyZeng. However, the code instruction changed too much.
Please help.

**Comment by JiatongBao** [comment]
@JackJrs 
Please provide specific hardware specifications. 

In the case of using low-performance GPU, you could try to use PyTorch AMP ( Automatic Mixed Precision)  to automatically handle mixed-precision training. AMP aims to improve the training speed and memory utilization while maintaining the desired model accuracy.

**Comment by gplminhduc147** [comment]
> @JackJrs Please provide specific hardware specifications.
> 
> In the case of using low-performance GPU, you could try to use PyTorch AMP ( Automatic Mixed Precision) to automatically handle mixed-precision training. AMP aims to improve the training speed and memory utilization while maintaining the desired model accuracy.

Hi. Sorry for my late. Here are my hardware:
CPU: Intel core i3-6100 CPU @ 3.70GHz (4 CPUs)
Graphic card: NVIDIA GeForce GTX 1660

**Comment by DucNguyenAIML** [comment]
> @JackJrs Please provide specific hardware specifications.
> 
> In the case of using low-performance GPU, you could try to use PyTorch AMP ( Automatic Mixed Precision) to automatically handle mixed-precision training. AMP aims to improve the training speed and memory utilization while maintaining the desired model accuracy.

Hi. Sorry for my late. Here are my hardware:
CPU: Intel core i3-6100 CPU @ 3.70GHz (4 CPUs)
Graphic card: NVIDIA GeForce GTX 1660

**Comment by JiatongBao** [comment]
@JackJrs The GTX 1660 is equipped with only 6 GB of GDDR5 memory. Maybe the current code cannot be directly run on this hardware setup.

We run the code with NVIDIA GTX 3090 which has 24 GB video memory.
